### ISSUE TITLE
Display Once Per Browser Session Option

### ISSUE THREAD

**Issue by JJRose** [Jmlevick/freenbarjs#1]
Hi.

I have just downloaded your script, which looks very nice and is also simple.  However there is no mention of whether it displays each time a page is opened. 

I am wanting the message to only pop up once per website visit.  So, the popup would be on every page, and when a visitor goes to the website (regardless of which page they land on), they will  only see that message once.  Till next visit.
The message is to inform visitors of a downtime period for maintenance and it would be very annoying to them to have to close the window for every page they visit during a session.

Is there a tweak that could be made to accommodate this? Or added as a yes/no option in the js?

Thanks in advance.

**Comment by Jmlevick** [comment]
Hi there!

The bar it's just a jquery widget that will display every time the script gets loaded, so in order to do what you wanna do this is not the correct level to look into (clientside), as you'll need some serverside logic implemented first and then in your view manage to use some other logic like "if first_visit == true... then don't load the bar script"

For example I wrote the bar to remind my users to login into my site to get comments analythics in the blog. Once a user was successfully logged in, the server would return a "current_user" variable to the views and if that variable was set then I didn't load the freenbar script so that logged in user wouldn't be bothered by it.

**Comment by JJRose** [comment]
Hi, yes, so is there some code that can be added into the js that would serve the purpose of just a visitor (eg by ip address and via cookies) that would achieve this?

**Comment by Jmlevick** [comment]
With just clientside code? Humm... Yes:

Store a variable called "visited" in user's *localStorage* and set it to something random; Then check for it's existence every time the freenbar.js script loads and if it exists then the user has already visited the site "for the first time", if it doesn't load the freenbarjs code. this logic can be achieved inside the freenbarjs main script like this (Coffeescript example):

```coffeescript
if localStorage.visited? is false
  #FreenbarJS code goes here
  localStorage.visited = "visited!"
```
